### ISSUE TITLE
Add Selection Sort in cpp

### ISSUE THREAD

**Issue by anweshabanerjee10** [kanisht09/Data-Structures-and-Algorithms#104] opened 2022-10-05 13:38 UTC

**Comment by roshan2152** [comment] 2022-10-05 13:47
@kanisht09  can i work on this?

**Comment by ShishuSidharth** [comment] 2022-10-05 14:02
Please assign this to me

**Comment by kanisht09** [comment] 2022-10-05 14:22
> @kanisht09 can i work on this?

hi there you can create a new issue if you want , if i feel the issue is worthy i will assign you to that issue. This issue is already been assigned so hope you understand !

**Closed** 2022-10-05 16:40 UTC
Labels: good first issue, hacktoberfest
